"""Download the themes' Google Fonts (open licences) into assets/fonts and write assets/css/fonts.css,
so the site works offline during the presentation. Springboard and Glass use the system font.

python3 website/tools/fonts.py
"""
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
FONTS = HERE / "assets" / "fonts"
CSS = HERE / "assets" / "css" / "fonts.css"
FAMILIES = [
    "Sora:wght@400;500;600;700;800",
    "Epilogue:wght@400;500;600;700;800",
    "Schibsted+Grotesk:wght@400;500;600;700;800;900",
    "IBM+Plex+Sans:wght@400;500;600;700",
    "IBM+Plex+Mono:wght@400;500;600",
    "Barlow:wght@400;500;600;700",
    "Barlow+Condensed:wght@500;600;700",
]
KEEP = {"latin", "latin-ext", "greek"}
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"


def get(url):
    # system curl: it uses the macOS certificate store (this Python build has none configured)
    return subprocess.run(["curl", "-sfL", "--max-time", "30", "-A", UA, url], check=True, capture_output=True).stdout


def main():
    FONTS.mkdir(parents=True, exist_ok=True)
    out = ["/* Generated by tools/fonts.py from Google Fonts (SIL Open Font License). */"]
    seen = {}
    for fam in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={fam}&display=swap").decode()
        for subset, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face\s*{[^}]+})", css):
            if subset not in KEEP:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            name = seen.get(url)
            if not name:
                family = re.search(r"font-family: '([^']+)'", block).group(1).replace(" ", "")
                name = f"{family}-{subset}-{len(seen)}.woff2"
                (FONTS / name).write_bytes(get(url))
                seen[url] = name
            out.append(block.replace(url, f"../fonts/{name}"))
    CSS.write_text("\n".join(out) + "\n")
    total = sum(p.stat().st_size for p in FONTS.glob("*.woff2"))
    print(len(seen), "files,", round(total / 1024), "KB ->", CSS)


if __name__ == "__main__":
    main()
